log:
  # level: DEBUG # change to WARN once everything is setup correctly
  level: WARN
  # filePath: /logs/traefik.log

accessLog:
  bufferingSize: 100
  filters:
    statusCodes:
      - "204-299"
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"

providers:
  docker:
    exposedByDefault: false
    endpoint: 'tcp://dockerproxy:2375'
    network: traefik-servicenet
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true # if you don't need the dashboard disable it

entryPoints:
  web:
    address: ':10080' # will be routed to port 80, see docker-compose.yaml
    http:
      redirections:   # redirect entire entrypoint to https
        entryPoint:
          to: ':443'
          scheme: https      
  web-secure:
    address: ':10443' # will be routed to port 443, see docker-compose.yaml
    http3:
      advertisedPort: 443

certificatesResolvers:
  tlschallenge:
    acme:
      # comment next line out for testing to not be throttled by LetsEncrypt
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme.json
      tlsChallenge: {}

experimental:
  http3: true
global:
  sendAnonymousUsage: true # set to false, if you don't want to send anonymous usage data
