http:
  middlewares:
    # prevent hammering of services
    rateLimiter:
      rateLimit:
        average: 100
        burst: 50
    # security headers
    secHeaders:
      headers:
        referrerPolicy: no-referrer
        forceSTSHeader: true
        frameDeny: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Powered-By: "Redstone"
          Server: "Server"
        customFrameOptionsValue: "SAMEORIGIN"
    # auth middlewares
    basicAuth:
      basicauth:
        removeheader: true
        usersfile: /etc/traefik/htpasswd
    traefikOauth:
      forwardAuth:
        address: "http://oauth:4181"
        trustForwardHeader: true
        authResponseHeaders: "X-Forwarded-User"
    # chain middlewares for cleaner compose files
    chainNoAuth:
      chain:
        middlewares:
          - rateLimiter
          - secHeaders
    chainBasicAuth:
      chain:
        middlewares:
          - rateLimiter
          - secHeaders
          - basicAuth
    chainOauth:
      chain:
        middlewares:
          - rateLimiter
          - secHeaders
          - traefikOauth